### PR TITLE
fix: close pending iterators before closing LevelDB store

### LINKED ISSUE #82: LevelDB datastore crashes if one attempts to close it while there are still iterators which haven't been disposed of
The description says it. If you try to do that, the program will crash with:

```text
leveldb::VersionSet::~VersionSet(): Assertion `dummy_versions_.next_ == &dummy_versions_' failed.
```

This is particularly common when shutting down the node.

### PR DESCRIPTION
**Pull request by gmega**
This PR adds tracking of open iterators to leveldbds so that when one attempts to close it, iterators are disposed of first. It also adds automatic disposal if iterators are completely consumed.

fixes #82

### CODE REVIEW

File: datastore/leveldb/leveldbds.nim [hunk 1]
```diff
@@ -98,6 +107,13 @@ method query*(
       limit = query.limit
     )
 
+  proc dispose(): Future[?!void] {.async: (raises: [CancelledError]).} =
+    dbIter.dispose()
+    iter.disposed = true
+    self.openIterators.excl(iter)
```
Comment (emizzle) [inline datastore/leveldb/leveldbds.nim:113]: Possible optimisation: check `iter.disposed` first?

**Review by emizzle — APPROVED** [review]

File: datastore/leveldb/leveldbds.nim (hunk 1 above)
Comment (gmega) [reply datastore/leveldb/leveldbds.nim:113]: Those are so fast and the operation so infrequent that's probably not even worth the trouble... (plus dbIter.dispose is idemptotent)
